// 页面逻辑继续按需加载，但场景样式必须从首屏开始可用。
// Rsbuild 开发模式下，懒加载的 vanilla-extract 样式首次进入可能晚于页面渲染；
// 集中注册可避免奖励、商店和事件页面短暂或持续出现裸样式。
import '@/features/archive/archivePage.css';
import '@/features/battle/battleHud.css';
import '@/features/battle/battlePage.css';
import '@/features/battle/reactBattleStage.css';
import '@/features/event/eventPage.css';
import '@/features/main-menu/mainMenu.css';
import '@/features/map/mapPage.css';
import '@/features/map/mapRoute.css';
import '@/features/overview/runOverview.css';
import '@/features/reward/rewardPage.css';
import '@/features/rest/restPage.css';
import '@/features/run-scene/runSceneShell.css';
import '@/features/run-scene/nodeResultOverlay.css';
import '@/features/shop/shopPage.css';
import '@/features/settlement/actTransitionPage.css';
import '@/features/settlement/settlementPage.css';
import '@/styles/sceneTheme.css';
import '@/styles/subscreen.css';
import '@/styles/uiPrimitives.css';
import './mobileLandscapeGate.css';
