import type { CardDefinition } from '../../../model/card';
import {
  STATUS_MOMENTUM,
  STATUS_METALLICIZE,
  STATUS_STEADY_GUARD,
  STATUS_STRENGTH,
  STATUS_VULNERABLE,
  STATUS_WEAK,
} from '../../statuses';

/**
 * 通用流派 - 生成卡组 D（53张）
 * 分布：15张普通攻/技混合 + 15张普通技能 + 13张稀有 + 10张史诗
 * 主题：万金油、少量连势触底、不过度偏向守势或爆发
 */

export const NEUTRAL_GENERATED_D: Record<string, CardDefinition> = {
  // =====================================================================
  //  第一批：15 张普通卡（攻/技混合，ch1）
  // =====================================================================

  nt_d_slash: {
    id: 'nt_d_slash',
    name: '斜劈',
    description: '造成 7 点伤害。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [{ type: 'damage', value: 7, target: 'selected' }],
    archetype: 'neutral',
    chapter: 1,
    tags: ['damage'],
  },

  nt_d_riposte: {
    id: 'nt_d_riposte',
    name: '反击',
    description: '造成 6 点伤害，获得 4 点格挡。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 6, target: 'selected' },
      { type: 'block', value: 4, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'block'],
  },

  nt_d_cleave_strike: {
    id: 'nt_d_cleave_strike',
    name: '横扫',
    description: '对所有敌人造成 5 点伤害。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    effects: [{ type: 'damage', value: 5, target: 'all_enemies' }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'aoe'],
  },

  nt_d_double_tap: {
    id: 'nt_d_double_tap',
    name: '二连击',
    description: '造成 3 点伤害两次。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [{ type: 'repeat', times: 2, effects: [{ type: 'damage', value: 3, target: 'selected' }] }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'multi_hit'],
  },

  nt_d_sunder: {
    id: 'nt_d_sunder',
    name: '裂甲',
    description: '造成 5 点伤害，施加 1 层易伤。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 5, target: 'selected' },
      { type: 'apply_status', statusId: STATUS_VULNERABLE, stacks: 1, target: 'selected' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'debuff'],
  },

  nt_d_hinder: {
    id: 'nt_d_hinder',
    name: '妨碍',
    description: '造成 4 点伤害，施加 1 层虚弱。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 4, target: 'selected' },
      { type: 'apply_status', statusId: STATUS_WEAK, stacks: 1, target: 'selected' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'debuff'],
  },

  nt_d_heavy_slash: {
    id: 'nt_d_heavy_slash',
    name: '重斩',
    description: '造成 12 点伤害。',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    target: 'single_enemy',
    effects: [{ type: 'damage', value: 12, target: 'selected' }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage'],
  },

  nt_d_quick_guard: {
    id: 'nt_d_quick_guard',
    name: '急防',
    description: '获得 6 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'block', value: 6, target: 'self' }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['block'],
  },

  nt_d_momentum_strike: {
    id: 'nt_d_momentum_strike',
    name: '顺势斩',
    description: '造成 6 点伤害。若你有连势，额外造成 3 点伤害。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 6, target: 'selected' },
      { type: 'custom', scriptId: 'momentum_burst_damage', params: { consumeMode: 'fixed', consumeValue: 0, baseDamage: 0, damagePerStack: 0 } },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'momentum'],
  },

  nt_d_scan_blow: {
    id: 'nt_d_scan_blow',
    name: '探察击',
    description: '造成 4 点伤害，抽 1 张牌。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 4, target: 'selected' },
      { type: 'draw', value: 1 },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'draw'],
  },

  nt_d_flank_strike: {
    id: 'nt_d_flank_strike',
    name: '侧袭',
    description: '造成 8 点伤害。施加 1 层易伤。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 8, target: 'selected' },
      { type: 'apply_status', statusId: STATUS_VULNERABLE, stacks: 1, target: 'selected' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'debuff'],
  },

  nt_d_siphon: {
    id: 'nt_d_siphon',
    name: '吸取',
    description: '造成 5 点伤害，回复 3 点生命。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 5, target: 'selected' },
      { type: 'heal', value: 3, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'heal'],
  },

  nt_d_ward: {
    id: 'nt_d_ward',
    name: '护罩',
    description: '获得 4 点格挡，获得 1 层力量。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 4, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 1, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['block', 'strength'],
  },

  nt_d_quick_dash: {
    id: 'nt_d_quick_dash',
    name: '快步',
    description: '造成 3 点伤害，获得 3 点格挡。',
    type: 'attack',
    rarity: 'common',
    cost: 0,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 3, target: 'selected' },
      { type: 'block', value: 3, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'block'],
  },

  nt_d_momentum_tap: {
    id: 'nt_d_momentum_tap',
    name: '借势轻击',
    description: '造成 3 点伤害两次。消耗 1 层连势，每层额外造成 1 点伤害。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'repeat', times: 2, effects: [{ type: 'damage', value: 3, target: 'selected' }] },
      { type: 'custom', scriptId: 'momentum_burst_damage', params: { consumeMode: 'fixed', consumeValue: 1, baseDamage: 0, damagePerStack: 1 } },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'momentum', 'multi_hit'],
  },

  // =====================================================================
  //  第二批：15 张普通技能卡
  // =====================================================================

  nt_d_fortify: {
    id: 'nt_d_fortify',
    name: '坚实',
    description: '获得 5 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'block', value: 5, target: 'self' }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['block'],
  },

  nt_d_iron_wall: {
    id: 'nt_d_iron_wall',
    name: '坚壁',
    description: '获得 8 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'block', value: 8, target: 'self' }],
    archetype: 'neutral',
    chapter: 1,
    tags: ['block'],
  },

  nt_d_glimpse: {
    id: 'nt_d_glimpse',
    name: '一瞥',
    description: '抽 2 张牌。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'draw', value: 2 }],
    archetype: 'neutral',
    chapter: 1,
    tags: ['draw'],
  },

  nt_d_surge: {
    id: 'nt_d_surge',
    name: '涌能',
    description: '获得 1 点能量。',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'none',
    effects: [{ type: 'gain_energy', value: 1 }],
    archetype: 'neutral',
    chapter: 1,
    tags: ['energy'],
  },

  nt_d_soothe: {
    id: 'nt_d_soothe',
    name: '抚慰',
    description: '回复 5 点生命。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'heal', value: 5, target: 'self' }],
    archetype: 'neutral',
    chapter: 1,
    tags: ['heal'],
  },

  nt_d_tenacity: {
    id: 'nt_d_tenacity',
    name: '韧性',
    description: '获得 2 层力量。',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'none',
    effects: [{ type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 2, target: 'self' }],
    archetype: 'neutral',
    chapter: 1,
    tags: ['strength'],
  },

  nt_d_discard_draw: {
    id: 'nt_d_discard_draw',
    name: '弃旧迎新',
    description: '弃 1 张牌，抽 2 张牌。',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'none',
    effects: [
      { type: 'discard', value: 1 },
      { type: 'draw', value: 2 },
    ],
    archetype: 'neutral',
    chapter: 1,
    tags: ['draw', 'discard'],
  },

  nt_d_defense_up: {
    id: 'nt_d_defense_up',
    name: '防御充能',
    description: '获得 4 点格挡，获得 1 层力量。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 4, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 1, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 1,
    tags: ['block', 'strength'],
  },

  nt_d_momentum_surge: {
    id: 'nt_d_momentum_surge',
    name: '蓄势涌动',
    description: '获得 2 层连势，抽 1 张牌。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 2, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    archetype: 'neutral',
    chapter: 1,
    tags: ['momentum', 'draw'],
  },

  nt_d_careful_step: {
    id: 'nt_d_careful_step',
    name: '谨慎步伐',
    description: '获得 3 点格挡，获得 2 层连势。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 3, target: 'self' },
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 2, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 1,
    tags: ['block', 'momentum'],
  },

  nt_d_inspire: {
    id: 'nt_d_inspire',
    name: '鼓舞',
    description: '获得 1 层力量，抽 1 张牌。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 1, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    archetype: 'neutral',
    chapter: 1,
    tags: ['strength', 'draw'],
  },

  nt_d_second_wind: {
    id: 'nt_d_second_wind',
    name: '回风',
    description: '获得 5 点格挡，获得 1 层连势。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 5, target: 'self' },
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 1, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 1,
    tags: ['block', 'momentum'],
  },

  nt_d_calibrate: {
    id: 'nt_d_calibrate',
    name: '校准',
    description: '抽 2 张牌，获得 2 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'draw', value: 2 },
      { type: 'block', value: 2, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 1,
    tags: ['draw', 'block'],
  },

  nt_d_cautious_retreat: {
    id: 'nt_d_cautious_retreat',
    name: '退守',
    description: '获得 7 点格挡。消耗。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'block', value: 7, target: 'self' }],
    exhaustOnPlay: true,
    archetype: 'neutral',
    chapter: 1,
    tags: ['block', 'exhaust'],
  },

  nt_d_momentum_guard: {
    id: 'nt_d_momentum_guard',
    name: '借势守御',
    description: '获得格挡。每层连势额外提供 2 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'custom', scriptId: 'momentum_guard_by_stacks', params: { baseBlock: 3, blockPerStack: 2 } }],
    archetype: 'neutral',
    chapter: 1,
    tags: ['block', 'momentum'],
  },

  // =====================================================================
  //  第三批：13 张稀有卡（攻/技/能力混合）
  // =====================================================================

  nt_d_ricochet: {
    id: 'nt_d_ricochet',
    name: '弹射',
    description: '对所有敌人造成 8 点伤害。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'all_enemies',
    effects: [{ type: 'damage', value: 8, target: 'all_enemies' }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'aoe'],
  },

  nt_d_flurry: {
    id: 'nt_d_flurry',
    name: '疾风连打',
    description: '造成 4 点伤害三次。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'single_enemy',
    effects: [{ type: 'repeat', times: 3, effects: [{ type: 'damage', value: 4, target: 'selected' }] }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'multi_hit'],
  },

  nt_d_piercing_thrust: {
    id: 'nt_d_piercing_thrust',
    name: '穿刺',
    description: '造成 10 点伤害，施加 2 层易伤。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 10, target: 'selected' },
      { type: 'apply_status', statusId: STATUS_VULNERABLE, stacks: 2, target: 'selected' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'debuff'],
  },

  nt_d_momentum_cleave: {
    id: 'nt_d_momentum_cleave',
    name: '借势横扫',
    description: '造成 5 点伤害两次。消耗 2 层连势，每层额外造成 2 点伤害。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'repeat', times: 2, effects: [{ type: 'damage', value: 5, target: 'selected' }] },
      { type: 'custom', scriptId: 'momentum_burst_damage', params: { consumeMode: 'fixed', consumeValue: 2, baseDamage: 0, damagePerStack: 2 } },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'momentum', 'multi_hit'],
  },

  nt_d_culling_blow: {
    id: 'nt_d_culling_blow',
    name: '斩除',
    description: '造成 14 点伤害。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'single_enemy',
    effects: [{ type: 'damage', value: 14, target: 'selected' }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage'],
  },

  nt_d_resilient_block: {
    id: 'nt_d_resilient_block',
    name: '韧性防御',
    description: '获得 10 点格挡。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: 'none',
    effects: [{ type: 'block', value: 10, target: 'self' }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['block'],
  },

  nt_d_bolster: {
    id: 'nt_d_bolster',
    name: '增援',
    description: '获得 8 点格挡，获得 2 层力量。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'block', value: 8, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 2, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['block', 'strength'],
  },

  nt_d_momentum_flourish: {
    id: 'nt_d_momentum_flourish',
    name: '连势绽放',
    description: '获得 3 层连势。消耗 1 层连势时额外抽 1 张牌。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 3, target: 'self' },
      { type: 'custom', scriptId: 'momentum_burst_draw', params: { consumeMode: 'fixed', consumeValue: 1, baseDraw: 1, drawPerStack: 0 } },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['momentum', 'draw'],
  },

  nt_d_metallicize: {
    id: 'nt_d_metallicize',
    name: '金属化',
    description: '获得 2 层金属化。',
    type: 'power',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [{ type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 2, target: 'self' }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['metallicize', 'scaling'],
  },

  nt_d_steady_stance: {
    id: 'nt_d_steady_stance',
    name: '稳势',
    description: '获得 1 层稳势。',
    type: 'power',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [{ type: 'apply_status', statusId: STATUS_STEADY_GUARD, stacks: 1, target: 'self' }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['steady_guard', 'scaling'],
  },

  nt_d_overwhelm: {
    id: 'nt_d_overwhelm',
    name: '压制',
    description: '造成 9 点伤害，获得 6 点格挡。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 9, target: 'selected' },
      { type: 'block', value: 6, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'block'],
  },

  nt_d_momentum_burst: {
    id: 'nt_d_momentum_burst',
    name: '连势爆发',
    description: '造成 4 点伤害。消耗所有连势，每层额外造成 2 点伤害。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'single_enemy',
    effects: [{ type: 'custom', scriptId: 'momentum_burst_damage', params: { consumeMode: 'all', baseDamage: 4, damagePerStack: 2 } }],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'momentum'],
  },

  nt_d_power_siphon: {
    id: 'nt_d_power_siphon',
    name: '力量汲取',
    description: '造成 8 点伤害。获得 1 层力量。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 8, target: 'selected' },
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 1, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 2,
    tags: ['damage', 'strength'],
  },

  // =====================================================================
  //  第四批：10 张史诗卡（攻/技/能力混合）
  // =====================================================================

  nt_d_judgement_cut: {
    id: 'nt_d_judgement_cut',
    name: '裁决之刃',
    description: '造成 20 点伤害。',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'single_enemy',
    effects: [{ type: 'damage', value: 20, target: 'selected' }],
    archetype: 'neutral',
    chapter: 3,
    tags: ['damage'],
  },

  nt_d_storm_slash: {
    id: 'nt_d_storm_slash',
    name: '风暴斩',
    description: '造成 5 点伤害四次。',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'single_enemy',
    effects: [{ type: 'repeat', times: 4, effects: [{ type: 'damage', value: 5, target: 'selected' }] }],
    archetype: 'neutral',
    chapter: 3,
    tags: ['damage', 'multi_hit'],
  },

  nt_d_momentum_unleash: {
    id: 'nt_d_momentum_unleash',
    name: '连势释放',
    description: '造成 8 点伤害。消耗所有连势，每层造成额外 4 点伤害。',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    target: 'single_enemy',
    effects: [{ type: 'custom', scriptId: 'momentum_burst_damage', params: { consumeMode: 'all', baseDamage: 8, damagePerStack: 4 } }],
    archetype: 'neutral',
    chapter: 3,
    tags: ['damage', 'momentum'],
  },

  nt_d_annihilation: {
    id: 'nt_d_annihilation',
    name: '毁灭横扫',
    description: '对所有敌人造成 14 点伤害。',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'all_enemies',
    effects: [{ type: 'damage', value: 14, target: 'all_enemies' }],
    archetype: 'neutral',
    chapter: 3,
    tags: ['damage', 'aoe'],
  },

  nt_d_citadel: {
    id: 'nt_d_citadel',
    name: '堡垒',
    description: '获得 18 点格挡。',
    type: 'skill',
    rarity: 'rare',
    cost: 2,
    target: 'none',
    effects: [{ type: 'block', value: 18, target: 'self' }],
    archetype: 'neutral',
    chapter: 3,
    tags: ['block'],
  },

  nt_d_momentum_draw_burst: {
    id: 'nt_d_momentum_draw_burst',
    name: '连势涌现',
    description: '抽 3 张牌。消耗 3 层连势，每层额外抽 1 张牌。',
    type: 'skill',
    rarity: 'rare',
    cost: 2,
    target: 'none',
    effects: [{ type: 'custom', scriptId: 'momentum_burst_draw', params: { consumeMode: 'fixed', consumeValue: 3, baseDraw: 3, drawPerStack: 1 } }],
    archetype: 'neutral',
    chapter: 3,
    tags: ['draw', 'momentum'],
  },

  nt_d_fortress: {
    id: 'nt_d_fortress',
    name: '要塞',
    description: '获得 3 层金属化。',
    type: 'power',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [{ type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 3, target: 'self' }],
    archetype: 'neutral',
    chapter: 3,
    tags: ['metallicize', 'scaling'],
  },

  nt_d_steady_fortification: {
    id: 'nt_d_steady_fortification',
    name: '稳固防线',
    description: '获得 2 层稳势，获得 10 点格挡。',
    type: 'skill',
    rarity: 'rare',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_STEADY_GUARD, stacks: 2, target: 'self' },
      { type: 'block', value: 10, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 3,
    tags: ['steady_guard', 'block'],
  },

  nt_d_mighty_blow: {
    id: 'nt_d_mighty_blow',
    name: '万钧一击',
    description: '造成 16 点伤害，获得 8 点格挡。',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 16, target: 'selected' },
      { type: 'block', value: 8, target: 'self' },
    ],
    archetype: 'neutral',
    chapter: 3,
    tags: ['damage', 'block'],
  },

  nt_d_momentum_overflow: {
    id: 'nt_d_momentum_overflow',
    name: '连势满溢',
    description: '获得 5 层力量，获得 2 层连势。消耗。',
    type: 'skill',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 5, target: 'self' },
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 2, target: 'self' },
    ],
    exhaustOnPlay: true,
    archetype: 'neutral',
    chapter: 3,
    tags: ['strength', 'momentum', 'exhaust'],
  },
};
