import type { CardDefinition } from '../../../model/card';
import {
  STATUS_MOMENTUM,
  STATUS_METALLICIZE,
  STATUS_STEADY_GUARD,
  STATUS_STRENGTH,
  STATUS_PRIMED_BREAK,
} from '../../statuses';

/**
 * 守势流派 - 生成卡组 C (55张)
 * 主题：防御、连势稳定、金属化、稳势
 * 分布：15 common skill + 10 common attack + 15 uncommon + 15 rare = 55
 */

export const GUARD_GENERATED_C: Record<string, CardDefinition> = {
  // =========================================================================
  // COMMON SKILL (15) — 格挡为主
  // =========================================================================

  gd_c_iron_wall: {
    id: 'gd_c_iron_wall',
    name: '钢壁',
    description: '获得 8 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'block', value: 8, target: 'self' }],
    archetype: 'guard',
    chapter: 1,
    tags: ['block'],
  },

  gd_c_stone_skin: {
    id: 'gd_c_stone_skin',
    name: '石化之肤',
    description: '获得 6 点格挡，获得 1 层金属化。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 6, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 1, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'metallicize'],
  },

  gd_c_bastion: {
    id: 'gd_c_bastion',
    name: '壁垒',
    description: '获得 5 点格挡，获得 1 层稳势。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 5, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STEADY_GUARD, stacks: 1, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'steady_guard'],
  },

  gd_c_fortify: {
    id: 'gd_c_fortify',
    name: '加固',
    description: '获得 4 点格挡，获得 2 层连势。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 4, target: 'self' },
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 2, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'momentum'],
  },

  gd_c_impenetrable: {
    id: 'gd_c_impenetrable',
    name: '坚不可摧',
    description: '获得 11 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 2,
    target: 'none',
    effects: [{ type: 'block', value: 11, target: 'self' }],
    archetype: 'guard',
    chapter: 2,
    tags: ['block'],
  },

  gd_c_rampart: {
    id: 'gd_c_rampart',
    name: '壁垒防御',
    description: '获得 3 点格挡，抽 1 张牌。',
    type: 'skill',
    rarity: 'common',
    cost: 0,
    target: 'none',
    effects: [
      { type: 'block', value: 3, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'draw'],
  },

  gd_c_steel_ward: {
    id: 'gd_c_steel_ward',
    name: '钢铁护佑',
    description: '获得 7 点格挡。若你有金属化，额外获得 3 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'custom', scriptId: 'momentum_guard_by_stacks', params: { baseBlock: 7, blockPerStack: 1 } }],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'metallicize'],
  },

  gd_c_guard_posture: {
    id: 'gd_c_guard_posture',
    name: '守卫姿态',
    description: '获得 5 点格挡，获得 1 层力量。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 5, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 1, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'strength'],
  },

  gd_c_iron_resolve: {
    id: 'gd_c_iron_resolve',
    name: '钢铁意志',
    description: '获得 6 点格挡，获得 2 层金属化。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 6, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 2, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'metallicize'],
  },

  gd_c_turtle_shell: {
    id: 'gd_c_turtle_shell',
    name: '龟壳',
    description: '获得 13 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 2,
    target: 'none',
    effects: [{ type: 'block', value: 13, target: 'self' }],
    archetype: 'guard',
    chapter: 2,
    tags: ['block'],
  },

  gd_c_steady_breath: {
    id: 'gd_c_steady_breath',
    name: '沉稳呼吸',
    description: '获得 4 点格挡，获得 2 层稳势。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 4, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STEADY_GUARD, stacks: 2, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'steady_guard'],
  },

  gd_c_warding_shout: {
    id: 'gd_c_warding_shout',
    name: '护佑呐喊',
    description: '对所有敌人造成 3 点伤害，获得 5 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'damage', value: 3, target: 'all_enemies' },
      { type: 'block', value: 5, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'damage'],
  },

  gd_c_anvil_stance: {
    id: 'gd_c_anvil_stance',
    name: '铁砧架势',
    description: '获得 9 点格挡。若你本回合未消耗连势，额外获得 3 点格挡。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [{ type: 'custom', scriptId: 'momentum_guard_by_stacks', params: { baseBlock: 9, blockPerStack: 1 } }],
    archetype: 'guard',
    chapter: 3,
    tags: ['block', 'momentum'],
  },

  gd_c_solid_ground: {
    id: 'gd_c_solid_ground',
    name: '坚实大地',
    description: '获得 7 点格挡，获得 1 层金属化和 1 层稳势。',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 7, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 1, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STEADY_GUARD, stacks: 1, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['block', 'metallicize', 'steady_guard'],
  },

  gd_c_last_stand: {
    id: 'gd_c_last_stand',
    name: '最后一搏',
    description: '获得 10 点格挡，抽 1 张牌。',
    type: 'skill',
    rarity: 'common',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'block', value: 10, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['block', 'draw'],
  },

  // =========================================================================
  // COMMON ATTACK (10) — 伤害 + 格挡混合
  // =========================================================================

  gd_c_shield_bash: {
    id: 'gd_c_shield_bash',
    name: '盾击',
    description: '造成 5 点伤害，获得 3 点格挡。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 5, target: 'selected' },
      { type: 'block', value: 3, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 1,
    tags: ['damage', 'block'],
  },

  gd_c_iron_strike: {
    id: 'gd_c_iron_strike',
    name: '铁击',
    description: '造成 6 点伤害，获得 2 层金属化。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 6, target: 'selected' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 2, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['damage', 'metallicize'],
  },

  gd_c_guard_slash: {
    id: 'gd_c_guard_slash',
    name: '守卫斩击',
    description: '造成 4 点伤害，获得 4 点格挡。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 4, target: 'selected' },
      { type: 'block', value: 4, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['damage', 'block'],
  },

  gd_c_sure_strike: {
    id: 'gd_c_sure_strike',
    name: '稳健出击',
    description: '造成 6 点伤害，施加 1 层易伤。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 6, target: 'selected' },
      { type: 'apply_status', statusId: 'vulnerable', stacks: 1, target: 'selected' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['damage', 'debuff'],
  },

  gd_c_wall_breaker: {
    id: 'gd_c_wall_breaker',
    name: '破壁之击',
    description: '造成等同于当前格挡值的伤害。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [{ type: 'custom', scriptId: 'block_to_damage', params: { multiplier: 1 } }],
    archetype: 'guard',
    chapter: 1,
    tags: ['damage', 'block_scaling'],
  },

  gd_c_defensive_cleave: {
    id: 'gd_c_defensive_cleave',
    name: '防御横扫',
    description: '对所有敌人造成 4 点伤害，获得 4 点格挡。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'all_enemies',
    effects: [
      { type: 'damage', value: 4, target: 'all_enemies' },
      { type: 'block', value: 4, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['damage', 'block', 'aoe'],
  },

  gd_c_riposte: {
    id: 'gd_c_riposte',
    name: '反击',
    description: '造成 8 点伤害。若你有格挡，额外造成 4 点伤害。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 8, target: 'selected' },
      { type: 'custom', scriptId: 'block_to_damage', params: { multiplier: 0.5 } },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['damage', 'block_scaling'],
  },

  gd_c_grounded_slash: {
    id: 'gd_c_grounded_slash',
    name: '落地斩',
    description: '造成 7 点伤害，获得 4 点格挡。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 7, target: 'selected' },
      { type: 'block', value: 4, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['damage', 'block'],
  },

  gd_c_guardian_lunge: {
    id: 'gd_c_guardian_lunge',
    name: '守卫突刺',
    description: '造成 5 点伤害两次。',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    target: 'single_enemy',
    effects: [{ type: 'repeat', times: 2, effects: [{ type: 'damage', value: 5, target: 'selected' }] }],
    archetype: 'guard',
    chapter: 3,
    tags: ['damage', 'multi_hit'],
  },

  gd_c_rampart_strike: {
    id: 'gd_c_rampart_strike',
    name: '壁垒重击',
    description: '造成 9 点伤害，获得 5 点格挡。',
    type: 'attack',
    rarity: 'common',
    cost: 2,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 9, target: 'selected' },
      { type: 'block', value: 5, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['damage', 'block'],
  },

  // =========================================================================
  // UNCOMMON (15) — 技能/攻击/能力混合
  // =========================================================================

  gd_c_fortification: {
    id: 'gd_c_fortification',
    name: '筑垒',
    description: '获得 12 点格挡，获得 2 层金属化。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'block', value: 12, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 2, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 1,
    tags: ['block', 'metallicize'],
  },

  gd_c_iron_clad: {
    id: 'gd_c_iron_clad',
    name: '铁甲护身',
    description: '造成 10 点伤害，获得等同于你金属化层数的格挡。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 10, target: 'selected' },
      { type: 'custom', scriptId: 'momentum_guard_by_stacks', params: { baseBlock: 0, blockPerStack: 1 } },
    ],
    archetype: 'guard',
    chapter: 1,
    tags: ['damage', 'metallicize'],
  },

  gd_c_steady_fortress: {
    id: 'gd_c_steady_fortress',
    name: '稳势堡垒',
    description: '获得 8 点格挡，获得 3 层稳势。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'block', value: 8, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STEADY_GUARD, stacks: 3, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 1,
    tags: ['block', 'steady_guard'],
  },

  gd_c_iron_maiden: {
    id: 'gd_c_iron_maiden',
    name: '铁女刑具',
    description: '造成 12 点伤害，施加 2 层易伤。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 12, target: 'selected' },
      { type: 'apply_status', statusId: 'vulnerable', stacks: 2, target: 'selected' },
    ],
    archetype: 'guard',
    chapter: 1,
    tags: ['damage', 'debuff'],
  },

  gd_c_momentum_surge: {
    id: 'gd_c_momentum_surge',
    name: '连势涌动',
    description: '获得 6 点格挡，获得 4 层连势。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    target: 'none',
    effects: [
      { type: 'block', value: 6, target: 'self' },
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 4, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'momentum'],
  },

  gd_c_warden_strike: {
    id: 'gd_c_warden_strike',
    name: '看守重击',
    description: '造成 14 点伤害。消耗 3 层连势。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 1,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 14, target: 'selected' },
      { type: 'custom', scriptId: 'momentum_guard_by_stacks', params: { baseBlock: 0, blockPerStack: 0 } },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['damage', 'momentum'],
  },

  gd_c_bulwark: {
    id: 'gd_c_bulwark',
    name: '壁障',
    description: '获得 10 点格挡，获得 1 层力量。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'block', value: 10, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 1, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'strength'],
  },

  gd_c_multi_parry: {
    id: 'gd_c_multi_parry',
    name: '多重格挡',
    description: '获得 6 点格挡两次。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [{ type: 'repeat', times: 2, effects: [{ type: 'block', value: 6, target: 'self' }] }],
    archetype: 'guard',
    chapter: 2,
    tags: ['block'],
  },

  gd_c_heavy_bash: {
    id: 'gd_c_heavy_bash',
    name: '重锤猛击',
    description: '造成 8 点伤害，获得 8 点格挡。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'single_enemy',
    effects: [
      { type: 'damage', value: 8, target: 'selected' },
      { type: 'block', value: 8, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['damage', 'block'],
  },

  gd_c_metallic_fortitude: {
    id: 'gd_c_metallic_fortitude',
    name: '金属韧性',
    description: '获得 5 层金属化。',
    type: 'power',
    rarity: 'uncommon',
    cost: 3,
    target: 'none',
    effects: [{ type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 5, target: 'self' }],
    archetype: 'guard',
    chapter: 2,
    tags: ['metallicize', 'scaling'],
  },

  gd_c_unyielding_will: {
    id: 'gd_c_unyielding_will',
    name: '不屈意志',
    description: '获得 3 层稳势和 2 层金属化。',
    type: 'power',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_STEADY_GUARD, stacks: 3, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 2, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['steady_guard', 'metallicize'],
  },

  gd_c_sentinel: {
    id: 'gd_c_sentinel',
    name: '哨兵',
    description: '造成 6 点伤害三次。每击获得 2 点格挡。',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    target: 'single_enemy',
    effects: [{ type: 'repeat', times: 3, effects: [{ type: 'damage', value: 6, target: 'selected' }, { type: 'block', value: 2, target: 'self' }] }],
    archetype: 'guard',
    chapter: 3,
    tags: ['damage', 'multi_hit', 'block'],
  },

  gd_c_aegis_power: {
    id: 'gd_c_aegis_power',
    name: '神盾之力',
    description: '获得 2 层力量和 2 层金属化。',
    type: 'power',
    rarity: 'uncommon',
    cost: 3,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 2, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 2, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['strength', 'metallicize'],
  },

  gd_c_bulwark_stance: {
    id: 'gd_c_bulwark_stance',
    name: '壁障架势',
    description: '获得 15 点格挡，抽 1 张牌。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'block', value: 15, target: 'self' },
      { type: 'draw', value: 1 },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['block', 'draw'],
  },

  gd_c_primed_defense: {
    id: 'gd_c_primed_defense',
    name: '预热防御',
    description: '获得 8 点格挡，获得 2 层破势预热。',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'block', value: 8, target: 'self' },
      { type: 'apply_status', statusId: STATUS_PRIMED_BREAK, stacks: 2, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['block', 'primed_break'],
  },

  // =========================================================================
  // RARE (15) — 技能/攻击/能力混合
  // =========================================================================

  gd_c_impenetrable_wall: {
    id: 'gd_c_impenetrable_wall',
    name: '不可逾越之墙',
    description: '获得 20 点格挡。',
    type: 'skill',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [{ type: 'block', value: 20, target: 'self' }],
    archetype: 'guard',
    chapter: 1,
    tags: ['block'],
  },

  gd_c_guardian_devastation: {
    id: 'gd_c_guardian_devastation',
    name: '守卫毁灭',
    description: '造成等同于你格挡值两倍的伤害。',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'single_enemy',
    effects: [{ type: 'custom', scriptId: 'block_to_damage', params: { multiplier: 2 } }],
    archetype: 'guard',
    chapter: 1,
    tags: ['damage', 'block_scaling'],
  },

  gd_c_eternal_fortress: {
    id: 'gd_c_eternal_fortress',
    name: '永恒堡垒',
    description: '获得 12 点格挡，获得 4 层金属化。',
    type: 'skill',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [
      { type: 'block', value: 12, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 4, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 1,
    tags: ['block', 'metallicize'],
  },

  gd_c_momentum_bastion: {
    id: 'gd_c_momentum_bastion',
    name: '连势壁垒',
    description: '获得 8 点格挡，获得 6 层连势。',
    type: 'skill',
    rarity: 'rare',
    cost: 2,
    target: 'none',
    effects: [
      { type: 'block', value: 8, target: 'self' },
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 6, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['block', 'momentum'],
  },

  gd_c_titan_slam: {
    id: 'gd_c_titan_slam',
    name: '巨人碾压',
    description: '造成 20 点伤害。消耗所有稳势，每层造成额外 5 点伤害。',
    type: 'attack',
    rarity: 'rare',
    cost: 3,
    target: 'single_enemy',
    effects: [{ type: 'custom', scriptId: 'block_to_damage', params: { multiplier: 3 } }],
    archetype: 'guard',
    chapter: 2,
    tags: ['damage', 'steady_guard'],
  },

  gd_c_metallic_mastery: {
    id: 'gd_c_metallic_mastery',
    name: '金属化精通',
    description: '获得 8 层金属化。',
    type: 'power',
    rarity: 'rare',
    cost: 4,
    target: 'none',
    effects: [{ type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 8, target: 'self' }],
    archetype: 'guard',
    chapter: 2,
    tags: ['metallicize', 'scaling'],
  },

  gd_c_steady_master: {
    id: 'gd_c_steady_master',
    name: '稳势大师',
    description: '获得 5 层稳势。',
    type: 'power',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [{ type: 'apply_status', statusId: STATUS_STEADY_GUARD, stacks: 5, target: 'self' }],
    archetype: 'guard',
    chapter: 2,
    tags: ['steady_guard', 'scaling'],
  },

  gd_c_momentum_lord: {
    id: 'gd_c_momentum_lord',
    name: '连势之王',
    description: '获得 8 层连势，抽 2 张牌。',
    type: 'skill',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 8, target: 'self' },
      { type: 'draw', value: 2 },
    ],
    archetype: 'guard',
    chapter: 2,
    tags: ['momentum', 'draw'],
  },

  gd_c_unstoppable_bulwark: {
    id: 'gd_c_unstoppable_bulwark',
    name: '不可阻挡之壁',
    description: '获得 15 点格挡，获得 3 层力量。',
    type: 'skill',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [
      { type: 'block', value: 15, target: 'self' },
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 3, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['block', 'strength'],
  },

  gd_c_guardian_wrath: {
    id: 'gd_c_guardian_wrath',
    name: '守卫之怒',
    description: '造成 15 点伤害四次。',
    type: 'attack',
    rarity: 'rare',
    cost: 4,
    target: 'single_enemy',
    effects: [{ type: 'repeat', times: 4, effects: [{ type: 'damage', value: 15, target: 'selected' }] }],
    archetype: 'guard',
    chapter: 3,
    tags: ['damage', 'multi_hit'],
  },

  gd_c_ultimate_defense: {
    id: 'gd_c_ultimate_defense',
    name: '终极防御',
    description: '获得 15 点格挡，获得 3 层金属化，抽 2 张牌。',
    type: 'skill',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [
      { type: 'block', value: 15, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 3, target: 'self' },
      { type: 'draw', value: 2 },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['block', 'metallicize', 'draw'],
  },

  gd_c_fortress_master: {
    id: 'gd_c_fortress_master',
    name: '堡垒大师',
    description: '获得 3 层力量和 5 层金属化。',
    type: 'power',
    rarity: 'rare',
    cost: 4,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_STRENGTH, stacks: 3, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 5, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['strength', 'metallicize'],
  },

  gd_c_breaking_guard: {
    id: 'gd_c_breaking_guard',
    name: '破势大师',
    description: '获得 4 层破势预热，获得 3 层连势。',
    type: 'power',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_PRIMED_BREAK, stacks: 4, target: 'self' },
      { type: 'apply_status', statusId: STATUS_MOMENTUM, stacks: 3, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['primed_break', 'momentum'],
  },

  gd_c_aegis_mastery: {
    id: 'gd_c_aegis_mastery',
    name: '神盾精通',
    description: '获得 6 层稳势和 4 层金属化。',
    type: 'power',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [
      { type: 'apply_status', statusId: STATUS_STEADY_GUARD, stacks: 6, target: 'self' },
      { type: 'apply_status', statusId: STATUS_METALLICIZE, stacks: 4, target: 'self' },
    ],
    archetype: 'guard',
    chapter: 3,
    tags: ['steady_guard', 'metallicize'],
  },

  gd_c_last_wall: {
    id: 'gd_c_last_wall',
    name: '最后壁垒',
    description: '获得 25 点格挡。消耗。',
    type: 'skill',
    rarity: 'rare',
    cost: 3,
    target: 'none',
    effects: [{ type: 'block', value: 25, target: 'self' }],
    exhaustOnPlay: true,
    archetype: 'guard',
    chapter: 3,
    tags: ['block', 'exhaust'],
  },
};
