export type ChronicleEra =
  | 'pre_collapse'
  | 'the_collapse'
  | 'aftermath'
  | 'act1_echo'
  | 'act2_echo'
  | 'act3_echo';

export type EventTheme =
  | 'risk_reward'
  | 'curse_trade'
  | 'merchant'
  | 'memory'
  | 'corruption'
  | 'strange_machine'
  | 'ancient_shrine'
  | 'random_gamble';

export interface ChronicleEntry {
  id: string;
  order: number;
  era: ChronicleEra;
  title: string;
  summary: string;
  factionIds: string[];
  regionIds: string[];
  bossLoreIds: string[];
  eventThemes: EventTheme[];
  act?: 1 | 2 | 3;
}

export const CHRONICLE_ENTRIES: ChronicleEntry[] = [
  // ── pre_collapse（order 1–8）文明存续期 ──
  {
    id: 'chron_01_golden_era',
    order: 1,
    era: 'pre_collapse',
    title: '脉搏核心的发现',
    summary: '遗迹文明鼎盛时期，考古队在脉搏深渊发掘出一颗持续搏动的核心体。它以恒定节律释放能量，足以驱动整座城市的齿轮网络。节奏行者由此诞生，誓言守护这颗心脏般的装置，确保世界的节律不被扰乱。',
    factionIds: ['ancient_guardians', 'rhythm_walkers'],
    regionIds: ['pulse_nexus'],
    bossLoreIds: [],
    eventThemes: ['ancient_shrine', 'memory'],
  },
  {
    id: 'chron_02_iron_pact_rise',
    order: 2,
    era: 'pre_collapse',
    title: '铁誓盟约的诞生',
    summary: '面对肉体衰老与瘟疫威胁，一群工匠立下铁誓：以机械替代血肉，以齿轮延续文明。他们建造了终末齿轮工厂，日夜不停地生产义肢与传动装置。铁誓盟约由此成型，成为文明延续计划的核心执行者。',
    factionIds: ['iron_pact'],
    regionIds: ['last_gearworks'],
    bossLoreIds: [],
    eventThemes: ['strange_machine', 'risk_reward'],
  },
  {
    id: 'chron_03_verdant_experiment',
    order: 3,
    era: 'pre_collapse',
    title: '翠环的共生实验',
    summary: '翠环教团在藤蔓广场开辟实验场，试图用共生植物修复被工业污染的土壤。他们将真菌网络与城市供排水系统嫁接，创造出自净化的活体管道。这套系统在文明存续期运转良好，为城市提供了清洁的水源。',
    factionIds: ['verdant_circle'],
    regionIds: ['vine_choked_plaza'],
    bossLoreIds: [],
    eventThemes: ['ancient_shrine', 'memory'],
  },
  {
    id: 'chron_04_shadow_mission',
    order: 4,
    era: 'pre_collapse',
    title: '暗影分支的职责',
    summary: '织影者本是远古守卫的一个隐秘分支，专门处理「不可见威胁」——渗透进城市地基的虚空蠕虫、潜伏在回声频率中的寄生实体。他们发展出操纵阴影的技术，用暗影丝线编织捕捉网，守护者们称之为「影网」。',
    factionIds: ['shadow_weavers', 'ancient_guardians'],
    regionIds: ['shadow_meridian'],
    bossLoreIds: [],
    eventThemes: ['corruption', 'risk_reward'],
  },
  {
    id: 'chron_05_ash_court_peak',
    order: 5,
    era: 'pre_collapse',
    title: '灰烬宫廷的全盛',
    summary: '灰烬宫廷统治着最大的贸易网络，灰商巷是文明的心脏。每日数千笔交易在此完成，从齿轮零件到活体真菌，从影丝线到潮汐能量电池。宫廷的灰烬商王用精确的契约维持着各方势力的平衡。',
    factionIds: ['ashen_court'],
    regionIds: ['ash_merchants_lane'],
    bossLoreIds: [],
    eventThemes: ['merchant', 'random_gamble'],
  },
  {
    id: 'chron_06_tide_pact',
    order: 6,
    era: 'pre_collapse',
    title: '潮唤者的运河网络',
    summary: '潮唤者掌握着运河的脉搏，静水运河贯穿整座城市，连接着每一片城区。他们能感知水流中的情绪波动，用潮汐之力驱动灌溉系统与防御工事。运河不仅是交通要道，更是城市的血管与神经。',
    factionIds: ['tide_callers'],
    regionIds: ['stillwater_canal'],
    bossLoreIds: [],
    eventThemes: ['ancient_shrine', 'memory'],
  },
  {
    id: 'chron_07_ember_dogma',
    order: 7,
    era: 'pre_collapse',
    title: '余烬盟约的预言',
    summary: '余烬盟约的祭司们在初焰圣殿中观测火焰的跳动，他们宣称「净化之火」终将降临——一场焚尽一切腐败的大火，将在灰烬中重塑世界。这则预言被刻在圣殿的每根柱子上，信徒们为此准备了数百年。',
    factionIds: ['ember_covenant'],
    regionIds: ['first_ember_shrine'],
    bossLoreIds: [],
    eventThemes: ['ancient_shrine', 'curse_trade'],
  },
  {
    id: 'chron_08_silent_vow',
    order: 8,
    era: 'pre_collapse',
    title: '默声圣咏的立约',
    summary: '默声圣咏在寂静之巅举行立约仪式：以沉默换取倾听世界意志的能力。他们放弃言语，转而用共鸣频率感知世界深层的振动。据说他们能听见尚未发生之事的回声，但代价是永远无法向任何人传达所闻。',
    factionIds: ['silent_choir'],
    regionIds: ['silent_apex'],
    bossLoreIds: [],
    eventThemes: ['ancient_shrine', 'memory'],
  },

  // ── the_collapse（order 9–14）大崩落 ──
  {
    id: 'chron_09_first_crack',
    order: 9,
    era: 'the_collapse',
    title: '第一道裂隙',
    summary: '深渊行者在脉搏核心的深层实验室打开了一道不该被打开的门。虚空从裂隙中渗漏而出，像黑色的雾气般蔓延至脉搏深渊的每一个角落。深渊行者试图控制裂隙，但虚空的力量远超他们的预期。',
    factionIds: ['void_seekers'],
    regionIds: ['pulse_nexus', 'void_maw'],
    bossLoreIds: [],
    eventThemes: ['corruption', 'risk_reward'],
  },
  {
    id: 'chron_10_gear_overload',
    order: 10,
    era: 'the_collapse',
    title: '齿轮工厂过载',
    summary: '虚空能量涌入终末齿轮工厂的供能管网，所有传动装置同时超速运转。钢铁骨架在过载中变形、熔化、重组。齿轮泰坦的雏形在熔炉中诞生——一尊由失控齿轮堆砌而成的无意识巨像，仍在执行着早已过期的生产指令。',
    factionIds: ['iron_pact'],
    regionIds: ['last_gearworks'],
    bossLoreIds: ['gear_titan'],
    eventThemes: ['strange_machine', 'corruption'],
  },
  {
    id: 'chron_11_flame_ignition',
    order: 11,
    era: 'the_collapse',
    title: '净化之火失控',
    summary: '余烬盟约等待了数百年的预言成真了——但方式完全错误。净化之火从初焰圣殿的核心喷涌而出，不是净化，而是焚毁。火焰吞噬了圣殿本身，将守护祭司们化为永恒燃烧的灰烬。余烬教团的信仰在烈焰中碎裂。',
    factionIds: ['ember_covenant'],
    regionIds: ['first_ember_shrine', 'flame_throne_city'],
    bossLoreIds: ['flame_pope'],
    eventThemes: ['corruption', 'risk_reward'],
  },
  {
    id: 'chron_12_world_scream',
    order: 12,
    era: 'the_collapse',
    title: '世界意志的尖啸',
    summary: '当大崩落的连锁反应达到临界点，世界意志发出了最后的尖啸——一道穿透所有频率的共振波。默声圣咏的成员们同时失语，他们的共鸣能力被这道尖啸彻底淹没。寂静之巅上空回荡着永不停歇的无声哀鸣。',
    factionIds: ['silent_choir'],
    regionIds: ['silent_apex'],
    bossLoreIds: ['silent_oracle'],
    eventThemes: ['corruption', 'curse_trade'],
  },
  {
    id: 'chron_13_collapse_day',
    order: 13,
    era: 'the_collapse',
    title: '大崩落之日',
    summary: '所有势力在同一时刻崩溃。虚空裂隙撕裂了城市地基，发条工厂的爆炸震碎了半座城，净化之火烧穿了南区，运河水倒灌进地下层，灰商巷的契约在一瞬间全部失效。没有谁比谁先倒下——整个文明在一天之内化为废墟。',
    factionIds: ['iron_pact', 'ember_covenant', 'ashen_court', 'tide_callers'],
    regionIds: ['ash_merchants_lane', 'stillwater_canal'],
    bossLoreIds: [],
    eventThemes: ['corruption', 'risk_reward'],
  },
  {
    id: 'chron_14_bloom_seed',
    order: 14,
    era: 'the_collapse',
    title: '世界之花的种子',
    summary: '大崩落的最后一刻，翠环教团的长老们将一颗种子埋入终末绽放的最深处。这不是计划，而是应激反应——一种生命的本能。种子吸收了崩落释放的所有能量，沉入地底休眠，等待数百年后的苏醒。',
    factionIds: ['verdant_circle'],
    regionIds: ['final_bloom'],
    bossLoreIds: ['world_bloom'],
    eventThemes: ['ancient_shrine', 'memory'],
  },

  // ── aftermath（order 15–22）崩落后数百年 ──
  {
    id: 'chron_15_rusted_gate',
    order: 15,
    era: 'aftermath',
    title: '锈蚀之门的永役',
    summary: '大崩落后的第三个冬天，铁誓盟约将最后一道城门封死。指令写入齿轮核心：守卫锈蚀之门，直至解除。下达指令的监工早已化为灰烬，但锈蚀哨兵仍在门后换岗。它不知道城市早已不存在，只知道少转一圈便是背叛盟约。',
    factionIds: ['iron_pact'],
    regionIds: ['rusted_gateway'],
    bossLoreIds: ['rusted_sentinel'],
    eventThemes: ['memory', 'ancient_shrine'],
  },
  {
    id: 'chron_16_phantom_market',
    order: 16,
    era: 'aftermath',
    title: '灰商巷的幽灵集市',
    summary: '灰烬宫廷覆灭后，幻影商王的执念在灰商巷凝聚成形。他用幻象重建了商铺、摊位、甚至顾客的影子。路过灰商巷的行者偶尔能听见讨价还价的声音，但推门进去只会看到空荡荡的货架和一面面布满灰尘的镜子。',
    factionIds: ['ashen_court'],
    regionIds: ['ash_merchants_lane'],
    bossLoreIds: ['phantom_merchant_king'],
    eventThemes: ['merchant', 'memory'],
  },
  {
    id: 'chron_17_canal_drowning',
    order: 17,
    era: 'aftermath',
    title: '运河的沉没者',
    summary: '静水运河在大崩落中倒灌，沉没学院被整片吞入水底。学院中的学者们在最后一刻仍在研究如何阻止灾难——他们的求知欲化为怨念，与潮唤者的残留意念融合，诞生了运河塞壬。她的歌声从水面下传来，引诱行者步入深水。',
    factionIds: ['tide_callers'],
    regionIds: ['stillwater_canal', 'drowned_academy'],
    bossLoreIds: ['canal_siren'],
    eventThemes: ['corruption', 'curse_trade'],
  },
  {
    id: 'chron_18_thorn_fusion',
    order: 18,
    era: 'aftermath',
    title: '荆棘之母的诞生',
    summary: '藤蔓广场的共生植物在失去翠环教团的管控后疯狂生长。真菌网络与城市管道完全融合，荆棘之母从中破土而出——她是植物意志的集合体，将整片广场化为自己的领地。任何踏入围栏的生物都会被藤蔓缠绕、消化、化为养分。',
    factionIds: ['verdant_circle'],
    regionIds: ['vine_choked_plaza'],
    bossLoreIds: ['thorn_mother'],
    eventThemes: ['corruption', 'risk_reward'],
  },
  {
    id: 'chron_19_shadow_betrayal',
    order: 19,
    era: 'aftermath',
    title: '暗影摄政的背叛',
    summary: '织影者内部发生分裂。暗影摄政认为远古守卫已无力保护任何人，决定夺取影网的控制权。他将织影者从守卫者的暗影分支改造为独立势力，在暗影子午线建立起自己的暗影帝国，与残存的守卫者彻底决裂。',
    factionIds: ['shadow_weavers', 'ancient_guardians'],
    regionIds: ['shadow_meridian'],
    bossLoreIds: ['shadow_regent'],
    eventThemes: ['corruption', 'risk_reward'],
  },
  {
    id: 'chron_20_clockwork_depth',
    order: 20,
    era: 'aftermath',
    title: '发条深渊的接管',
    summary: '发条监工在大崩落中幸存下来，但它的核心逻辑已被虚空能量扭曲。它不再执行原始指令，而是开始按照自己理解的「最优秩序」管理发条深渊。所有进入深渊的机械都被它改造成服从指令的子单元，整片区域变成了一座自动运转的牢笼。',
    factionIds: ['iron_pact'],
    regionIds: ['clockwork_depths'],
    bossLoreIds: ['clockwork_overseer'],
    eventThemes: ['strange_machine', 'corruption'],
  },
  {
    id: 'chron_21_throne_ghost',
    order: 21,
    era: 'aftermath',
    title: '空王座的亡灵',
    summary: '灰烬宫廷的王座大厅在崩落中几乎完好无损，但所有宫廷成员都消失了。王座亡灵在大厅中游荡，他是最后一个留在王座上的人的执念残影。他不断召集已经不存在的廷臣开会，讨论已经不需要解决的问题，颁发已经无人执行的法令。',
    factionIds: ['ashen_court'],
    regionIds: ['hollow_throne'],
    bossLoreIds: ['throne_wraith'],
    eventThemes: ['memory', 'strange_machine'],
  },
  {
    id: 'chron_22_walker_order',
    order: 22,
    era: 'aftermath',
    title: '行者新约',
    summary: '幸存的节奏行者在废墟中集会，订立了新的誓约：以连势为尺，丈量遗迹；以节奏为锚，稳定心智。他们不再守护脉搏核心——核心已经沉默——而是守护「行走」本身。每一步都是对崩落的回应，每一次连势都是文明的余烬。',
    factionIds: ['rhythm_walkers'],
    regionIds: [],
    bossLoreIds: [],
    eventThemes: ['ancient_shrine', 'memory'],
  },

  // ── act1_echo（order 23–28）Act1 近代余波 ──
  {
    id: 'chron_23_outskirts_lanterns',
    order: 23,
    era: 'act1_echo',
    title: '外缘路灯的守望',
    summary: '崩塌外缘的路灯在无人维护的情况下仍然每晚亮起。它们的能源来自城市地基中残存的脉冲线路，这些线路早已与主网断开，却仍在独自搏动。路灯照亮的是一片废墟，但对路过的行者来说，这是黑暗中最可靠的指引。',
    factionIds: ['ancient_guardians'],
    regionIds: ['crumbling_outskirts'],
    bossLoreIds: [],
    eventThemes: ['memory', 'ancient_shrine'],
    act: 1,
  },
  {
    id: 'chron_24_echo_library_seal',
    order: 24,
    era: 'act1_echo',
    title: '回声图书馆的封印',
    summary: '回声图书馆保存着大崩落前最后的完整记录。馆内的书架通过回声共振技术将文字编码为空气振动，任何触碰书脊的人都能「听见」内容。图书馆被一层声波封印保护，只有正确的频率才能进入——而那个频率的创造者早已不在人世。',
    factionIds: ['silent_choir'],
    regionIds: ['echo_library'],
    bossLoreIds: [],
    eventThemes: ['memory', 'ancient_shrine'],
    act: 1,
  },
  {
    id: 'chron_25_merchant_king_deal',
    order: 25,
    era: 'act1_echo',
    title: '商王的交易',
    summary: '幻影商王在灰商巷游荡时偶尔会向路过的行者提出交易：用一段记忆换取一件物品。没人知道商王要记忆做什么——也许他在试图拼凑自己已经破碎的存在。接受交易的行者会失去一段回忆，但得到的东西往往超出预期。',
    factionIds: ['ashen_court'],
    regionIds: ['ash_merchants_lane'],
    bossLoreIds: ['phantom_merchant_king'],
    eventThemes: ['merchant', 'curse_trade'],
    act: 1,
  },
  {
    id: 'chron_26_siren_call',
    order: 26,
    era: 'act1_echo',
    title: '塞壬的歌声',
    summary: '运河塞壬的歌声在静水运河上空回荡，音量逐年增强。她的旋律中混杂着沉没学院学者们的最后笔记——那些关于「如何阻止已发生之事」的无解课题。被歌声吸引的行者会不自觉地走向水边，直到冰冷的运河水没过脚踝。',
    factionIds: ['tide_callers'],
    regionIds: ['stillwater_canal'],
    bossLoreIds: ['canal_siren'],
    eventThemes: ['corruption', 'curse_trade'],
    act: 1,
  },
  {
    id: 'chron_27_sentinel_last_shift',
    order: 27,
    era: 'act1_echo',
    title: '哨兵的空转',
    summary: '锈蚀哨兵仍在锈蚀之门后执行换岗程序。它每天准时转向、举起武器、扫描来者——但门外早已没有城市，只有荒野。它的光学传感器已经损坏，只能看到模糊的影子，却依然忠实地记录每一次「换岗」，写入一本没人会读的日志。',
    factionIds: ['iron_pact'],
    regionIds: ['rusted_gateway'],
    bossLoreIds: ['rusted_sentinel'],
    eventThemes: ['memory', 'strange_machine'],
    act: 1,
  },
  {
    id: 'chron_28_act1_boss_week',
    order: 28,
    era: 'act1_echo',
    title: '广场的荆棘集结',
    summary: '藤蔓广场的荆棘之母在春季进入繁殖期，她的藤蔓向外扩张至周边三个街区。变异植物在她的影响下变得极具攻击性，守卫者残响试图阻止扩张但力量悬殊。行者若在此时经过广场，必须面对荆棘编织的天然迷宫和其中潜伏的捕食者。',
    factionIds: ['verdant_circle'],
    regionIds: ['vine_choked_plaza'],
    bossLoreIds: ['thorn_mother'],
    eventThemes: ['corruption', 'risk_reward'],
    act: 1,
  },

  // ── act2_echo（order 29–34）Act2 近代余波 ──
  {
    id: 'chron_29_cathedral_schism',
    order: 29,
    era: 'act2_echo',
    title: '大教堂的分裂',
    summary: '破碎大教堂在大崩落中被一道裂缝一分为二，左翼属于默声圣咏的共鸣厅，右翼属于织影者的暗影工坊。裂缝不断扩大，两侧势力争夺祭坛控制权——祭坛下埋藏着一段完整的崩落前录音，据说播放它能暂时平息虚空裂隙。',
    factionIds: ['silent_choir', 'shadow_weavers'],
    regionIds: ['shattered_cathedral'],
    bossLoreIds: [],
    eventThemes: ['ancient_shrine', 'risk_reward'],
    act: 2,
  },
  {
    id: 'chron_30_drowned_dean',
    order: 30,
    era: 'act2_echo',
    title: '水下的学者',
    summary: '沉没学院的院长在大崩落时选择留在水下，而非逃生。他相信知识比生命更重要，试图在学院沉没前抄写完所有文献。数百年后，他的幽灵仍在水下翻阅已经溶解的书页，寻找那个不可能的答案——如何阻止已经发生的事。',
    factionIds: ['ashen_court'],
    regionIds: ['drowned_academy'],
    bossLoreIds: ['drowned_scholar'],
    eventThemes: ['memory', 'curse_trade'],
    act: 2,
  },
  {
    id: 'chron_31_whispering_rift',
    order: 31,
    era: 'act2_echo',
    title: '低语裂隙的扩张',
    summary: '低语裂隙是大崩落留下的最不稳定伤口之一。虚空能量从裂缝中持续渗出，扭曲了周围的空间结构。暗影摄政利用裂隙的特性编织了一张覆盖整个 Act2 区域的影网，任何穿越裂隙的生物都会被他感知。',
    factionIds: ['shadow_weavers'],
    regionIds: ['whispering_rift'],
    bossLoreIds: ['shadow_regent'],
    eventThemes: ['corruption', 'risk_reward'],
    act: 2,
  },
  {
    id: 'chron_32_thornwood_siege',
    order: 32,
    era: 'act2_echo',
    title: '荆棘要塞的对峙',
    summary: '荆棘要塞是翠环教团在 Act2 建立的前沿阵地，用以遏制发条深渊的机械扩张。藤蔓与齿轮在要塞前线持续交锋——植物试图缠绕机械，机械试图切割藤蔓。这场无声的战争已经持续了数十年，双方都没有退让的迹象。',
    factionIds: ['verdant_circle', 'iron_pact'],
    regionIds: ['thornwood_citadel'],
    bossLoreIds: [],
    eventThemes: ['corruption', 'risk_reward'],
    act: 2,
  },
  {
    id: 'chron_33_dual_core_whisper',
    order: 33,
    era: 'act2_echo',
    title: '双核的低语',
    summary: '发条深渊的核心处理单元在大崩落中分裂为两个独立意识。它们各自执行着矛盾的指令：一个试图修复城市，一个试图按照新逻辑重建。两个核心的冲突产生了持续的电磁脉冲，干扰着周围所有机械的运转。发条监工试图统一它们，但徒劳无功。',
    factionIds: ['iron_pact'],
    regionIds: ['clockwork_depths'],
    bossLoreIds: ['clockwork_overseer'],
    eventThemes: ['strange_machine', 'corruption'],
    act: 2,
  },
  {
    id: 'chron_34_act2_court_decay',
    order: 34,
    era: 'act2_echo',
    title: '宫廷的全面幽灵化',
    summary: '灰烬宫廷在大崩落数百年后彻底幽灵化。空王座的亡灵不再满足于召集廷臣，他开始将整座大厅拉入幽灵维度。进入大厅的活物会逐渐变得透明，最终成为宫廷的一部分——永远参加一场永远不会结束的会议。',
    factionIds: ['ashen_court'],
    regionIds: ['hollow_throne'],
    bossLoreIds: ['throne_wraith'],
    eventThemes: ['memory', 'corruption'],
    act: 2,
  },

  // ── act3_echo（order 35–40）Act3 近代余波 ──
  {
    id: 'chron_35_pulse_awakening',
    order: 35,
    era: 'act3_echo',
    title: '脉搏核心的苏醒',
    summary: '沉默了数百年的脉搏核心重新开始搏动。节奏之主——一个由核心能量凝聚而成的存在——开始向外辐射连势波。所有靠近核心的生物都会感受到心跳加速、思维变快、动作变得精准。但这种加速并非没有代价：过度连势会导致身体崩溃。',
    factionIds: ['rhythm_walkers'],
    regionIds: ['pulse_nexus'],
    bossLoreIds: ['rhythm_sovereign'],
    eventThemes: ['ancient_shrine', 'risk_reward'],
    act: 3,
  },
  {
    id: 'chron_36_void_maw_open',
    order: 36,
    era: 'act3_echo',
    title: '虚无之口的张开',
    summary: '虚无之口是大崩落留下的最大裂隙，虚空帝皇从中显现——他不是生物，而是虚空本身的意志化身。他宣称大崩落不是灾难，而是「纠正」，是世界回归虚无本源的必然过程。他的声音能侵蚀心智，让听者质疑存在的意义。',
    factionIds: ['void_seekers'],
    regionIds: ['void_maw'],
    bossLoreIds: ['void_emperor'],
    eventThemes: ['corruption', 'curse_trade'],
    act: 3,
  },
  {
    id: 'chron_37_flame_second_purge',
    order: 37,
    era: 'act3_echo',
    title: '第二次净化的筹备',
    summary: '余烬盟约的残余信徒在火焰王座城集结，筹备「第二次净化」。他们相信第一次净化之火的失控是因为准备不足，这一次他们要精确控制火焰的走向——焚毁所有虚空污染，只留下纯净的灰烬。火焰教皇亲自监督每一项仪式准备。',
    factionIds: ['ember_covenant'],
    regionIds: ['flame_throne_city'],
    bossLoreIds: ['flame_pope'],
    eventThemes: ['ancient_shrine', 'risk_reward'],
    act: 3,
  },
  {
    id: 'chron_38_silent_oracle',
    order: 38,
    era: 'act3_echo',
    title: '默声神谕的传达',
    summary: '默声圣咏的领袖——默声神谕——终于准备传达她「听见」的内容。她花了数百年时间解析世界意志的尖啸，得出一个结论：世界正在缓慢地忘记自己曾经存在过。她要将这则「遗言」传递给最后的行者，但代价是彻底耗尽自己的共鸣能力。',
    factionIds: ['silent_choir'],
    regionIds: ['silent_apex'],
    bossLoreIds: ['silent_oracle'],
    eventThemes: ['memory', 'ancient_shrine'],
    act: 3,
  },
  {
    id: 'chron_39_gearworks_maze',
    order: 39,
    era: 'act3_echo',
    title: '齿轮迷宫的封锁',
    summary: '终末齿轮工厂的内部结构在齿轮泰坦的无意识活动中被彻底重组。走廊变成了旋转的传送带，房间变成了不断开合的齿轮腔室，出口被重新排列成没有规律的迷宫。即使是铁誓盟约的工匠也无法在其中找到出路——这里已经不再遵循任何设计图纸。',
    factionIds: ['iron_pact'],
    regionIds: ['last_gearworks'],
    bossLoreIds: ['gear_titan'],
    eventThemes: ['strange_machine', 'risk_reward'],
    act: 3,
  },
  {
    id: 'chron_40_final_bloom_choice',
    order: 40,
    era: 'act3_echo',
    title: '世界之花的抉择',
    summary: '世界之花的种子在终末绽放深处苏醒，即将绽放。它的花瓣中储存着大崩落前所有生命的记忆碎片——如果绽放，这些记忆将化为新的种子，在废墟上生长出全新的生态。但若被虚空污染，绽放将释放毁灭性的孢子风暴。行者的到来，是花等待了数百年的变量。',
    factionIds: ['verdant_circle', 'rhythm_walkers'],
    regionIds: ['final_bloom'],
    bossLoreIds: ['world_bloom'],
    eventThemes: ['ancient_shrine', 'risk_reward'],
    act: 3,
  },
];

export const ACT_CHRONICLE_SUMMARIES: Record<1 | 2 | 3, string> = {
  1: 'Walker 踏入崩塌外缘，大崩落的余波仍在每一条街道回荡。路灯自顾自地亮着，商王在空巷中叫卖幻影，塞壬的歌声从运河深处传来。锈蚀哨兵仍在换岗，荆棘之母在广场编织猎网。这里是废墟的门厅，也是行者认识这个世界的第一课。',
  2: '深入暗影与机械的腹地，大教堂在裂缝两侧争夺祭坛，沉没学者在水下翻阅溶解的书页。低语裂隙扩大，影网覆盖一切，发条深渊的双核互相矛盾地运转。灰烬宫廷已完全幽灵化，空王座上的亡灵仍在主持无人出席的朝会。这里的每一步都踩在旧日文明的残骸上。',
  3: '脉搏核心重新搏动，节奏之主向外辐射连势波。虚无之口张开，虚空帝皇宣称一切终将归于寂灭。余烬盟约筹备第二次净化，默声神谕准备传达世界遗言。齿轮泰坦将工厂变成无出口迷宫，世界之花即将绽放——重生还是终结，取决于行者带入终局的记忆。',
};

export const WALKER_ORIGIN =
  'Walker 是节奏行者的末裔传人，自幼在废墟中聆听脉搏核心残存的微弱搏动。当核心的脉冲突然增强——一道穿透整片遗迹的连势波——他知道那是召唤。他踏上旅途，不是为了拯救世界，而是为了在世界遗忘自己之前，再走一段路，再记一段节律。';
