export interface Region {
  id: string;
  name: string;
  description: string;
  chapter: 1 | 2 | 3;
  faction: string;
  dangerLevel: number;
  keyFeature: string;
}

export const REGIONS: Record<string, Region> = {
  // Chapter 1 - 遗迹边缘，相对安全的区域
  crumbling_outskirts: {
    id: "crumbling_outskirts",
    name: "崩塌外缘",
    description: "古城遗迹的最外围，破碎的建筑残骸散落在荒芜的土地上。这里是大多数行者的起点，残存的路灯依然会在黄昏时分亮起微弱的光芒，仿佛在等待早已不会归来的居民。",
    chapter: 1,
    faction: "ancient_guardians",
    dangerLevel: 2,
    keyFeature: "自动亮起的遗迹路灯",
  },
  vine_choked_plaza: {
    id: "vine_choked_plaza",
    name: "藤蔓缠绕的广场",
    description: "曾经繁华的集市广场如今被变异的藤蔓完全覆盖，粗壮的根系穿透了石板地面，将整个广场变成了一片诡异的绿色海洋。空气中弥漫着甜腻的花香，但那些花朵似乎有自己的意志。",
    chapter: 1,
    faction: "verdant_circle",
    dangerLevel: 3,
    keyFeature: "会移动的变异藤蔓",
  },
  rusted_gateway: {
    id: "rusted_gateway",
    name: "锈蚀之门",
    description: "通往城市深处的巨大铁门已经锈蚀得无法正常开启，铁誓盟约的工匠们试图修复它，但每次齿轮转动都会发出刺耳的哀鸣。门后的阴影中似乎有什么东西在等待。",
    chapter: 1,
    faction: "iron_pact",
    dangerLevel: 3,
    keyFeature: "半开的巨型铁门与门后的低语",
  },
  ash_merchants_lane: {
    id: "ash_merchants_lane",
    name: "灰商巷",
    description: "曾经的商业街如今只剩下灰烬与残骸，但仍有商贩在这里摆摊贩卖从废墟中挖掘出的遗物。他们的面容模糊不清，仿佛随时都会消散在风中。",
    chapter: 1,
    faction: "ashen_court",
    dangerLevel: 2,
    keyFeature: "贩卖虚幻货物的幽灵商贩",
  },
  stillwater_canal: {
    id: "stillwater_canal",
    name: "静水运河",
    description: "城市中曾经繁忙的运河如今水面静止如镜，倒映出的不是天空，而是另一个世界的景象。偶尔水面会泛起涟漪，仿佛有什么东西正从水底窥视着你。",
    chapter: 1,
    faction: "tide_callers",
    dangerLevel: 4,
    keyFeature: "映照异世界的静止水面",
  },
  echo_library: {
    id: "echo_library",
    name: "回声图书馆",
    description: "巨大的图书馆依然保持着文明覆灭前的模样，但书中的文字会在无人时自行更改。默声圣咏的僧侣们驻守于此，试图解读那些不断变化的文字中隐藏的预言。",
    chapter: 1,
    faction: "silent_choir",
    dangerLevel: 3,
    keyFeature: "自行更改内容的书籍",
  },
  first_ember_shrine: {
    id: "first_ember_shrine",
    name: "初火圣坛",
    description: "余烬盟约的第一座圣殿，建在城市边缘的一座半塌陷的神庙中。圣坛中央燃烧着一团永不熄灭的火焰，据说这是毁灭世界那场大火中唯一被保存下来的火种。",
    chapter: 1,
    faction: "ember_covenant",
    dangerLevel: 4,
    keyFeature: "永不熄灭的初火",
  },

  // Chapter 2 - 遗迹核心，危险加剧
  shadow_meridian: {
    id: "shadow_meridian",
    name: "暗影子午线",
    description: "城市的中轴线如今被永恒的阴影笼罩，无论太阳如何移动，这里的黑暗都不会消散。织影者在此建立了一座看不见的堡垒，只有被选中的人才能踏入这片黑暗。",
    chapter: 2,
    faction: "shadow_weavers",
    dangerLevel: 6,
    keyFeature: "永恒不变的阴影区域",
  },
  shattered_cathedral: {
    id: "shattered_cathedral",
    name: "破碎大教堂",
    description: "城市中心最宏伟的建筑如今只剩下一半的穹顶和断裂的彩色玻璃。阳光穿过残存的玻璃投射出诡异的光影，每一束光线都像是某种古老仪式的残余。",
    chapter: 2,
    faction: "ancient_guardians",
    dangerLevel: 7,
    keyFeature: "投射幻象的残存彩色玻璃",
  },
  clockwork_depths: {
    id: "clockwork_depths",
    name: "发条深渊",
    description: "铁誓盟约在城市地下建造的巨大机械工厂，无数齿轮仍在不知疲倦地转动，但没有人记得它们最初的目的。工厂深处传来的敲击声，仿佛是某种巨大心脏的跳动。",
    chapter: 2,
    faction: "iron_pact",
    dangerLevel: 7,
    keyFeature: "自动运转的巨型机械",
  },
  drowned_academy: {
    id: "drowned_academy",
    name: "沉没学院",
    description: "曾经培养学者与法师的学院如今沉入了地下湖中，只有部分建筑露出水面。水下依然可以看到完好的教室与实验室，仿佛时间在这里凝固了。",
    chapter: 2,
    faction: "tide_callers",
    dangerLevel: 6,
    keyFeature: "水下完好的古代教室",
  },
  thornwood_citadel: {
    id: "thornwood_citadel",
    name: "荆棘要塞",
    description: "翠环教团的核心领地，一座完全由活体植物构成的城堡。墙壁会呼吸，走廊会移动，访客必须获得植物的认可才能找到正确的道路。要塞中央的古树据说已经存活了数千年。",
    chapter: 2,
    faction: "verdant_circle",
    dangerLevel: 6,
    keyFeature: "会移动的活体植物城堡",
  },
  hollow_throne: {
    id: "hollow_throne",
    name: "空王座",
    description: "灰烬宫廷的权力中心，一座悬浮在废墟上空的宫殿。宫殿中陈列着无数华丽的王座，但没有一把是为人准备的——它们是为早已消逝的国王们保留的。",
    chapter: 2,
    faction: "ashen_court",
    dangerLevel: 7,
    keyFeature: "悬浮的幽灵宫殿",
  },
  whispering_rift: {
    id: "whispering_rift",
    name: "低语裂隙",
    description: "深渊行者发现的巨大裂隙，从裂隙深处不断传来无数声音的低语，有时是请求，有时是警告，有时是疯狂的笑声。裂隙周围的物质会缓慢地被吞噬，仿佛虚无本身在扩张。",
    chapter: 2,
    faction: "void_seekers",
    dangerLevel: 8,
    keyFeature: "不断扩张的虚空裂隙",
  },

  // Chapter 3 - 遗迹核心，终局区域
  pulse_nexus: {
    id: "pulse_nexus",
    name: "脉搏核心",
    description: "节奏行者的圣地，位于城市最深处的巨型圆形大厅。大厅中央有一颗巨大的心脏状物体在缓慢跳动，每一次跳动都会产生肉眼可见的波动，影响着整个遗迹的节奏。",
    chapter: 3,
    faction: "rhythm_walkers",
    dangerLevel: 9,
    keyFeature: "影响现实的巨型心脏",
  },
  void_maw: {
    id: "void_maw",
    name: "虚无之口",
    description: "深渊行者最终的目标，一道通往虚无本源的巨大裂口。裂口周围的一切都在缓慢地崩解、消散，仿佛这个世界正在被一只无形的巨口吞噬。站在裂口边缘，你能听到世界碎裂的声音。",
    chapter: 3,
    faction: "void_seekers",
    dangerLevel: 10,
    keyFeature: "吞噬世界的巨大裂口",
  },
  flame_throne_city: {
    id: "flame_throne_city",
    name: "炎座之城",
    description: "余烬盟约的最终圣城，整座城市燃烧着永不熄灭的火焰。高温扭曲了空气，使远处的景象如同幻影。城市的中心是一座由熔岩构成的王座，据说坐上去的人将获得净化世界的力量。",
    chapter: 3,
    faction: "ember_covenant",
    dangerLevel: 10,
    keyFeature: "永燃的火焰圣城",
  },
  silent_apex: {
    id: "silent_apex",
    name: "寂静之巅",
    description: "默声圣咏的最高修道院，建在遗迹最高的塔楼中。这里没有声音，没有风，甚至没有时间的流逝感。修士们在这里进行最后的冥想，试图与这个世界残留的意志达成最后的对话。",
    chapter: 3,
    faction: "silent_choir",
    dangerLevel: 9,
    keyFeature: "绝对寂静的塔顶空间",
  },
  last_gearworks: {
    id: "last_gearworks",
    name: "终末齿轮工厂",
    description: "铁誓盟约最后的杰作，一座试图重启整个城市运转系统的巨型工厂。工厂的规模超乎想象，内部的空间似乎被扭曲了，走廊无限延伸，房间层层嵌套。",
    chapter: 3,
    faction: "iron_pact",
    dangerLevel: 9,
    keyFeature: "空间扭曲的巨型工厂",
  },
  final_bloom: {
    id: "final_bloom",
    name: "终末绽放",
    description: "翠环教团预言中的终极之地，一朵巨大的变异花朵即将在这里绽放。据说这朵花的绽放将决定世界的命运——要么带来全新的生机，要么释放出足以毁灭一切的孢子。",
    chapter: 3,
    faction: "verdant_circle",
    dangerLevel: 10,
    keyFeature: "即将绽放的终极变异花",
  },
};
